# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
